name: Validate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: nasa-gcn/.github/.github/workflows/node.yml@main
    with:
      test-options:
  bump:
    name: dry run of version bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20.x'
      - name: Configure git identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Install package
        run: npm ci
      - name: Bump version
        run: npm version patch
      - name: Run validation
        run: npm test
